name: Manubot
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  manubot:
    name: Manubot
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Set Environment Variables
        run: |
          TRIGGERING_SHA=${GITHUB_PULL_REQUEST_SHA:-$GITHUB_SHA}
          TRIGGERING_SHA_7=${TRIGGERING_SHA::7}
          echo "::set-env name=TRIGGERING_SHA_7::$TRIGGERING_SHA_7"
          echo "TRIGGERING_SHA: $TRIGGERING_SHA"
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # fetch entire commit history to support get_rootstock_commit
          fetch-depth: 0
      - name: Install Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Build Manuscript
        shell: bash --login {0}
        run: bash build/build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: manuscript-${{ github.run_id }}-${{ env.TRIGGERING_SHA_7 }}
          path: output
      # - name: Deploy Manuscript
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   env:
      #     MANUBOT_SSH_PRIVATE_KEY: ${{ secrets.MANUBOT_SSH_PRIVATE_KEY }}
      #     CI_BUILD_WEB_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
      #     CI_JOB_WEB_URL: https://github.com/${{ github.repository }}/runs/${{ github.run_id }}
      #   shell: bash --login {0}        
      #   run: |
      #     if [ "$MANUBOT_SSH_PRIVATE_KEY" != "" ]; then
      #       bash ci/deploy.sh
      #     else
      #       echo >&2 "Skipping deployment because the MANUBOT_SSH_PRIVATE_KEY secret is not set.
      #       Instructions at https://github.com/manubot/rootstock/blob/master/SETUP.md#deploy-key"
      #     fi
      - name: Deploy Output
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3.0.4-0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
          # commit_message: todo
          # user_name: todo
          # user_email: todo@peaceiris.com
      - name: Configure Webpage
        shell: bash --login {0}
        run: |
          manubot webpage \
            --timestamp \
            --no-ots-cache \
            --checkout=gh-pages \
            --version="${{ github.sha }}"
      - name: Deploy Webpage
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3.0.4-0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webpage
          publish_branch: gh-pages
